### ISSUE TITLE
Potential panic due to nil map in parsing frames

### ISSUE THREAD

**Issue by jschwinger233** [rmedvedev/grpcdump#10]
https://github.com/rmedvedev/grpcdump/blob/7111a41c418df186392784bc78f8cbd057711592/internal/app/framereader/framereader.go#L75-L90

With the header `grpc-status` ~~(usually happened when an application or runtime error occurs during an RPC)~~, the frame will be marked as `isTrailer = true` in L77, and fall into condition branch in L82. But there is no guarantee that `stream.MetaHeaders` map in L84 has been initiated, and such carelessness would cause panic.

**Comment by rmedvedev** [comment]
fixed
