### ISSUE TITLE
Doesn't work on OSX / Mac

### ISSUE THREAD

**Issue by esnible** [rmedvedev/grpcdump#11]
FYI:

```
go run cmd/grpcdump/main.go

internal/app/packetprovider/ethernetprovider.go:12:11: undefined: pcapgo.EthernetHandle
internal/app/packetprovider/ethernetprovider.go:17:18: undefined: pcapgo.NewEthernetHandle
```

I realize this is not your fault; github.com/google/gopacket/pcapgo uses `// +build linux,go1.9` directives.  Maybe a note in the doc to save others from going down this route.

**Comment by rmedvedev** [comment]
Hi, thank you for useful comment. I appended warning to readme.
